### ISSUE TITLE
pruner --help doesn't show --watch and its alias

### ISSUE THREAD

**Issue by MartinSkovsen** [pruner/cli#2]
<img width="1018" alt="Screenshot 2020-11-06 at 10 16 02" src="https://user-images.githubusercontent.com/30232520/98348555-31ff0580-2019-11eb-96e3-eeafbf040ae6.png">

**Comment by ffMathy** [comment]
This is by design. It does not show the help options for sub-commands.

Writing `pruner run` or `pruner run --help` shows the proper flags.
