### ISSUE TITLE
Display red for failing tests in gutters

### ISSUE THREAD

**Issue by MartinSkovsen** [pruner/cli#3]

**Comment by ffMathy** [comment]
The state now contains the result and duration of each test. The LCOV should also reflect this in the latest build, but I have not yet tested it, so I'll leave this issue open.

**Comment by ffMathy** [comment]
Alright, that worked. But only on initial run if the state is empty. It seems the merge of previous and current state prefers the test outcome of the previous test run.

![image](https://user-images.githubusercontent.com/2824010/98481453-95945900-21fa-11eb-882d-5dae1a60c3fe.png)

I'll get that fixed the next time I can, and close the issue.

**Comment by ffMathy** [comment]
Fixed!
