### ISSUE TITLE
Dotnet provider puts coverage file in test folder instead of working directory

### ISSUE THREAD

**Issue by MartinSkovsen** [pruner/cli#48]
Imagine I have a folder structure like: src/Tests/UnitTests/CrazyTests.cs, my .csproj file is located at src/Tests/Tests.csproj, and my pruner configured working directory is src/Tests. Under these circumstances, it looks like Pruner puts the coverage file near the actual test class in /UnitTests. However, when running pruner run it seems to be looking for a coverage file in src/Tests

**Comment by MartinSkovsen** [comment]
Nevermind, this was a mistake on my part. The described behaviour does not occur.

**Comment by ffMathy** [comment]
<3
