### ISSUE TITLE
Pruner creates folder with trailing space

### ISSUE THREAD

**Issue by OlafMerkert** [pruner/cli#61]
When running pruner through the command `npx --package=@pruner/cli pruner run`, it creates a folder `.pruner-bin/bin `, where the folder "bin " has a trailing space.

**Comment by OlafMerkert** [comment]
Probably coming from the trailing space in the ES string template literal at https://github.com/pruner/cli/blob/65dc98f2d6c5f5d27c2144cda5aadd88193829b3/src/providers/dotnet/arguments.ts#L68

**Comment by ffMathy** [comment]
Ah good catch! I'll get that fixed as soon as I'm back at my computer. Alternatively if you make a PR, I can accept it from my phone.

**Comment by ffMathy** [comment]
This has now been resolved.

**Comment by OlafMerkert** [comment]
Thank you!
