### ISSUE TITLE
The future of the product

### ISSUE THREAD

**Issue by 0x2025** [pruner/cli#90]
Hi @ffMathy 

I'm looking for a live unit testing tool on .NET and know this project, appreciate your hard work.
As I see from git history it has been a few years that you have been working on and stopped code changes a year ago. What is your perspective on continuing to develop this project and how it helps you improve your productivity? would love to know your perspective.
Disclaim: I a fan of continues testing, and TDD, and a huge believer that live unit testing will improve my productivity. Other products (NCrunch, VS Enterprise, dotUltimate) are expensive to me.

**Comment by ffMathy** [comment]
Hey!

I'm glad you're checking out my project.

I am fairly certain Pruner should still work and be stable.

I haven't contributed for some time, but it is certainly not dead 😊

Do you use Visual Studio or VS Code?

**Comment by 0x2025** [comment]
Hi @ffMathy  Thank you for the information. I'm using the Visual Studio Community and my workflow is to execute the test manually so I'm evaluating Pruner.

**Comment by 0x2025** [comment]
@ffMathy  Given I just closed this issue but would like to ask, does Pruner utilize the benefit of Hot Reload in .NET?

**Comment by ffMathy** [comment]
> @ffMathy Given I just closed this issue but would like to ask, does Pruner utilize the benefit of Hot Reload in .NET?

Sure thing! All questions are welcome.

No, unfortunately not. Pruner supports several languages, but the architecture and approach for all of them is the same.

**Comment by ffMathy** [comment]
> @ffMathy Given I just closed this issue but would like to ask, does Pruner utilize the benefit of Hot Reload in .NET?

Sure thing! All questions are welcome.

No, unfortunately not. Pruner supports several languages, but the architecture and approach for all of them is the same.

**Comment by 0x2025** [comment]
Thank @ffMathy.
